dist: trusty
language: node_js
sudo: required
node_js: '6'
branches:
  except:
    - gh-pages
addons:
  firefox: "45.0"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  global:
    - secure: sE/qqaaWjoYN2ln1lpqfWWd/S2J/zPJnanUcOrpZR+/ts5pgr9UnXIbCHA2YvEGg8/dpHono5TvqihY1aDy5mozGSlsbZSpqpkwN4Iei9rc5amTsBIynRAFyba6e8511XHzjITWiqb8eDqvkEg3cJKKFA/pyT++zXloKOhnMd2w7gharbcEqtnFc+d8Y/GVkvzFgb97ESTqvM3q905LHBzo0mEPijbP8gW/JESS2bz8BDnbfQrqXWECqFGTKVxV8cT/N7KpsCuDo345R5M+fgTvffEmber7yAhI1C0YdBdt+Lsp0KdpGlw8FMyhT5qlhisF26NPZNUPmcfkLqXtbkiOhfYRIQuOOAQxVgEOeQE/p5IhDjyTjvyCDeUjeSOvthuvmRQWZCg2twr7g/qMHNXWhP20h6UDtDdr+XYVNjZ1L7dcUKUHEL41u7iU8OR+AWk+TKv/12MIJA6jTLdHFw1QC7utA3zNaRMAfakRxNRU4ekRSpDTZjvIdjdfx4PaVR8nW6ryPaXkosGZYS8m3/aGsAuF5KuzFxlfzKhJvg5xz0MfFbbnUt/FjMRbxyroHWi1agvwM4G50ep1Pu3XVkU+TIfffulU2PrJKSOj8/3wa35CGJWWkR2kdpxCSZRSJz16aDTxiObtybTqhqNEjHQotwpTs+mlIQ2H5Fp4HT00=
    - secure: WPpcdS1O1Eh3HUsqsY1IliYcET3dSKJ9deUjKESNoZKjhQsVPg+OTYCQTIfnL0sLH1l+Fh9aE0mbp20Css9SgHa1anGsbGVk3tEWDPmYZdqmu+AUkIMsTJPC0c96pkHzIMR2Ewt3ZilqxIR7p+eD2F7H/ej7BwabywMKQYaQ86pEFs7TfGkaZ2bU5t9boCQMY7usbCkbKIshjwh+z3jnKvuxAam7Q/LyCM+ZwHe5hW9CzB10P0dOntNICWVihvEvGAtWm3klrULuxAJnmysLH+N0AYms0BzmiQm+hMuoEyHo0B9DLa2vapq13SnLgGJnJOoveos7pGeqVEb0FIZB8bxg9q/ZnpcPzwrenbS2ckokQ0EVSAMzgHWQrl1TXbFCAEaQd3pZ8ncW+y7vc6qPbrX7WLaZqyxnv9lfmrsgzvoY7qjywRQynesgije5EMLxTd33a0plwFKVJkDAynR5qsrKAYKwgPz+IYx2cZoJY2An1DnxxUof7uBi/n0DcTmDQVVVllduOpga52l3FtfZ5DlOp2ghX5EPF//ParT3OkOKf/Sz/9RiQAWzr2zejsuRF30cZB5WXs9Px/tYdblfPtP99xA8ZmQV3UVNehU/lRGbHlpMqlHx+WsiL8dQNzjhUh9vDxxKWScAQO2VbCF6vfYEJ8zqTuDwy+zJ5mYTbVE=
    - GH_REF=github.com/wburgers/websocket-component.git
    - secure: sSIqNcjL3ETUtjN7mzdVWLRa4X+xbIhBKxqJ3BSn7bWceTsWnbyK0bWIuOv4yljlIJDvTtIIrYzTeq+2LM7NUloIxs/U+zyj94LrCVl5lW8t+yjl+Vs/waY1CXT3Niv+X8hD++Fo2g7wro2BXjszPhzRsHN/aeqxuhQy0D90xxcywy71SP0NajTu5fq/lU5IkdDzc1D50uYU65aTqxiUF1rl19c1uYka5rnKEgJsVMvHvTHTgVBIW4hArZViwwpVYVmhGq4550Se1pyCG5z8W+v357XDYiZRxAM/yGkM2sRTL6u7lSsoLdp8qGO+q7RYDMt6lwL7rifcvEeb15Hp0YKxakYX0b7PQAomQNjTuARYMVelc6XbtgR69HsBgBuDK4rLES+vzhncJ5J8RggE97z4WMIfLsWunQLzB1ERXAYKhmhrdC3Kph9DUXzo2lUZfJUSsVpnDijMWY7ADr2ubWG2cgjHU1J+1u3sEJeN8dgyhgD/CXCVBo7e949SWJdSvN0O1gvSQnmYCIQEM8brX1t50T5JyFdL9GBRjUPELX4rFruvSsNd9lr3/lmhXJXyJSC40otP+YBtb2aQUuEn2UzqBoEOccMJv2kKn+/x6uKaYuA8OkK/VZBuiCCjafYwT/Q7mIIbsQmPSz9c/DTZuhIWfAe373TVELtS4HgGm8Q=
before_script:
  - npm install -g bower web-component-tester
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
script:
  - xvfb-run wct --skip-plugin sauce
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi'
after_success:
  - bash ./ghpages_deploy.sh wburgers websocket-component
